'use strict';

/**
* Orchestrator for the subModules which together generate a customized wikipedia
* package.
*/

const path = require('path')
const categoryListGenerator = require('./category_list_generator');
const articleListGenerator = require('./article_list_generator');
const packageGenerator = require('./package_generator');

/**
 * Intermediate files used and generated by different modules.
 *
 * All files are present relative to the project's root directory.
 */

/**
 * The name of the file that would contain the list of (possibly partial)
 * Wikipedia categories one in each line. The list specifies the list of
 * categories to search.
 *
 * Typical generation method:
 *
 *     Obtain the latest dump of all categories from 'dumps.wikimedia.org' and
 *     extract the category names from it using a substitution.
 *
 *     For example, the following 'vim' substitution:
 *
 *       %s/([09][09]*,'\([aZAZ09\.\,\&()][aZAZ09\.\,\&()]*\)',[09][09]*,[09][09]*,[09][09]*),/\1\r/
 *
 *     would extract most of the category names.
 *
 * Generated by: External source (Preprocessed Wikimedia dump)
 * Used by:      Category list generator
 */
const enwikiCatsFileName = 'enwiki-cats-bigger-preprocessed';

/**
 * The name of the file that would contain the list of articles to be present in
 * the offline package.
 *
 * Generated by: Article list generator
 * Used by:      Package generator
 */
const articleListFileName = 'article-list';

/**
 * The name of the directory into which the ZIM file would be generated.
 */
const zimOutputDirName ='public/output';

const generatePackage = function (params, packageCallback) {
    const commonPath = path.resolve(__dirname, '.');
    const enwikiCatsFile = path.resolve(commonPath, enwikiCatsFileName);
    const articleListFile = path.resolve(commonPath, articleListFileName);
    const zimOutputDir = path.resolve(commonPath, zimOutputDirName);
    const packageOptions = {
        nopic: params.nopic,
        novid: params.novid
    };

    const categoryListCallback = function (categories) {
        articleListGenerator.generateArticleList(
            categories,
            articleListFile,
            articleListCallback
        );
    };

    const articleListCallback = function () {
        packageGenerator.generateZimPackage(
            articleListFile,
            zimOutputDir,
            packageOptions,
            packageGeneratorCallback
        );
    };

    const packageGeneratorCallback = function (outputFile) {
        packageCallback(outputFile);
    };

    try {
        categoryListGenerator.generateCategoryList(
            params.userQuery,
            enwikiCatsFile,
            categoryListCallback
        );
    }
    catch (error) {
        throw error;
    }
};

exports.generatePackage = generatePackage;
// generatePackage({userQuery: 'abdul kalam'}, function(outputFile) {
//     console.log('Package callback:', outputFile);
// });
