'use strict'

/**
 * Orchestrator for the sub-modules which together generate a customized wikipedia
 * package.
 */

const category_list_generator = require ('category_list_generator')
const article_list_generator = require ('article_list_generator')
const package_generator = require ('package_generator')

/**
 * Intermediate files used and generated by different modules.
 *
 * All files are present relative to the project's root directory.
 */

/**
 * The name of the file that would contain the list of (possibly partial)
 * Wikipedia categories one in each line. The list specifies the list of
 * categories to search.
 *
 * Generated by: External source (Preprocessed Wikimedia dump)
 * Used by:      Category list generator
 */
const enwiki_cats_file_name = 'enwiki-cats-bigger'

/**
 * The name of the file that would contain the list of categories using which
 * the list of articles that belong to that category or one of it's children
 * would be generated.
 *
 * Generated by: Category list generator
 * Used by:      Article list generator
 */
const category_list_file_name = 'categoryList'

/**
 * The name of the file that would contain the list of articles to be present in
 * the offline package.
 *
 * Generated by: Article list generator
 * Used by:      Package generator
 */
const article_list_file_name = 'articleList'

/**
 * The name of the directory into which the ZIM file would be generated.
 */
const zim_output_dir_name ='public/output'

function generate_package (user_query) {
	try {
		category_list_generator.generate_category_list (user_query,
		                                                enwiki_cats_file_name,
		                                                category_list_file_name)
		article_list_generator.generate_article_list (category_list_file_name,
		                                              article_list_file_name)
		package_generator.generate_zim_package (article_list_file_name,
		                                        zim_output_dir_name)
	}
	catch (error) {
		throw error
	}
}

generate_package ('sudoku')
